import { $, Glob, write } from "bun"

const schemasGlob = new Glob("./apps/**/db/schema.ts")
const schemaFiles = await Array.fromAsync(schemasGlob.scan("."))

const imports = schemaFiles.map((file) => {
  return `export * from "@/${file.replace("./apps/", "").replace(".ts", "")}"`
})

const content = `// File generated by bun run db:generate:imports\n${imports.join("\n")}\n`

write("./packages/db/schema.ts", content)

await $`biome check --write ./packages/db/schema.ts`

console.log("✅ @/db: Schema imports generated!")
